//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASClient.PASService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sei/", ConfigurationName="PASService.IFileHandlerSEI")]
    public interface IFileHandlerSEI {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/uploadRequest", ReplyAction="http://sei/IFileHandlerSEI/uploadResponse")]
        PASClient.PASService.uploadResponse upload(PASClient.PASService.uploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/uploadRequest", ReplyAction="http://sei/IFileHandlerSEI/uploadResponse")]
        System.Threading.Tasks.Task<PASClient.PASService.uploadResponse> uploadAsync(PASClient.PASService.uploadRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/getClassificationRequest", ReplyAction="http://sei/IFileHandlerSEI/getClassificationResponse")]
        PASClient.PASService.getClassificationResponse getClassification(PASClient.PASService.getClassificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/getClassificationRequest", ReplyAction="http://sei/IFileHandlerSEI/getClassificationResponse")]
        System.Threading.Tasks.Task<PASClient.PASService.getClassificationResponse> getClassificationAsync(PASClient.PASService.getClassificationRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/classifyRequest", ReplyAction="http://sei/IFileHandlerSEI/classifyResponse")]
        PASClient.PASService.classifyResponse classify(PASClient.PASService.classifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/classifyRequest", ReplyAction="http://sei/IFileHandlerSEI/classifyResponse")]
        System.Threading.Tasks.Task<PASClient.PASService.classifyResponse> classifyAsync(PASClient.PASService.classifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/createTreeRequest", ReplyAction="http://sei/IFileHandlerSEI/createTreeResponse")]
        void createTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/createTreeRequest", ReplyAction="http://sei/IFileHandlerSEI/createTreeResponse")]
        System.Threading.Tasks.Task createTreeAsync();
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/uploadChatFileRequest", ReplyAction="http://sei/IFileHandlerSEI/uploadChatFileResponse")]
        PASClient.PASService.uploadChatFileResponse uploadChatFile(PASClient.PASService.uploadChatFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/uploadChatFileRequest", ReplyAction="http://sei/IFileHandlerSEI/uploadChatFileResponse")]
        System.Threading.Tasks.Task<PASClient.PASService.uploadChatFileResponse> uploadChatFileAsync(PASClient.PASService.uploadChatFileRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/downloadRequest", ReplyAction="http://sei/IFileHandlerSEI/downloadResponse")]
        PASClient.PASService.downloadResponse download(PASClient.PASService.downloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sei/IFileHandlerSEI/downloadRequest", ReplyAction="http://sei/IFileHandlerSEI/downloadResponse")]
        System.Threading.Tasks.Task<PASClient.PASService.downloadResponse> downloadAsync(PASClient.PASService.downloadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="upload", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.uploadRequestBody Body;
        
        public uploadRequest() {
        }
        
        public uploadRequest(PASClient.PASService.uploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class uploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public uploadRequestBody() {
        }
        
        public uploadRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadResponse", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.uploadResponseBody Body;
        
        public uploadResponse() {
        }
        
        public uploadResponse(PASClient.PASService.uploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class uploadResponseBody {
        
        public uploadResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClassificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClassification", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.getClassificationRequestBody Body;
        
        public getClassificationRequest() {
        }
        
        public getClassificationRequest(PASClient.PASService.getClassificationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getClassificationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getClassificationRequestBody() {
        }
        
        public getClassificationRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClassificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClassificationResponse", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.getClassificationResponseBody Body;
        
        public getClassificationResponse() {
        }
        
        public getClassificationResponse(PASClient.PASService.getClassificationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getClassificationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public getClassificationResponseBody() {
        }
        
        public getClassificationResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class classifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="classify", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.classifyRequestBody Body;
        
        public classifyRequest() {
        }
        
        public classifyRequest(PASClient.PASService.classifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class classifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public classifyRequestBody() {
        }
        
        public classifyRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class classifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="classifyResponse", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.classifyResponseBody Body;
        
        public classifyResponse() {
        }
        
        public classifyResponse(PASClient.PASService.classifyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class classifyResponseBody {
        
        public classifyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadChatFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadChatFile", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.uploadChatFileRequestBody Body;
        
        public uploadChatFileRequest() {
        }
        
        public uploadChatFileRequest(PASClient.PASService.uploadChatFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class uploadChatFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public uploadChatFileRequestBody() {
        }
        
        public uploadChatFileRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadChatFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadChatFileResponse", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.uploadChatFileResponseBody Body;
        
        public uploadChatFileResponse() {
        }
        
        public uploadChatFileResponse(PASClient.PASService.uploadChatFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class uploadChatFileResponseBody {
        
        public uploadChatFileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="download", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.downloadRequestBody Body;
        
        public downloadRequest() {
        }
        
        public downloadRequest(PASClient.PASService.downloadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public downloadRequestBody() {
        }
        
        public downloadRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadResponse", Namespace="http://sei/", Order=0)]
        public PASClient.PASService.downloadResponseBody Body;
        
        public downloadResponse() {
        }
        
        public downloadResponse(PASClient.PASService.downloadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public downloadResponseBody() {
        }
        
        public downloadResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileHandlerSEIChannel : PASClient.PASService.IFileHandlerSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileHandlerSEIClient : System.ServiceModel.ClientBase<PASClient.PASService.IFileHandlerSEI>, PASClient.PASService.IFileHandlerSEI {
        
        public FileHandlerSEIClient() {
        }
        
        public FileHandlerSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileHandlerSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileHandlerSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileHandlerSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PASClient.PASService.uploadResponse PASClient.PASService.IFileHandlerSEI.upload(PASClient.PASService.uploadRequest request) {
            return base.Channel.upload(request);
        }
        
        public void upload(string arg0, string arg1) {
            PASClient.PASService.uploadRequest inValue = new PASClient.PASService.uploadRequest();
            inValue.Body = new PASClient.PASService.uploadRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            PASClient.PASService.uploadResponse retVal = ((PASClient.PASService.IFileHandlerSEI)(this)).upload(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PASClient.PASService.uploadResponse> PASClient.PASService.IFileHandlerSEI.uploadAsync(PASClient.PASService.uploadRequest request) {
            return base.Channel.uploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<PASClient.PASService.uploadResponse> uploadAsync(string arg0, string arg1) {
            PASClient.PASService.uploadRequest inValue = new PASClient.PASService.uploadRequest();
            inValue.Body = new PASClient.PASService.uploadRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((PASClient.PASService.IFileHandlerSEI)(this)).uploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PASClient.PASService.getClassificationResponse PASClient.PASService.IFileHandlerSEI.getClassification(PASClient.PASService.getClassificationRequest request) {
            return base.Channel.getClassification(request);
        }
        
        public byte[] getClassification(string arg0) {
            PASClient.PASService.getClassificationRequest inValue = new PASClient.PASService.getClassificationRequest();
            inValue.Body = new PASClient.PASService.getClassificationRequestBody();
            inValue.Body.arg0 = arg0;
            PASClient.PASService.getClassificationResponse retVal = ((PASClient.PASService.IFileHandlerSEI)(this)).getClassification(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PASClient.PASService.getClassificationResponse> PASClient.PASService.IFileHandlerSEI.getClassificationAsync(PASClient.PASService.getClassificationRequest request) {
            return base.Channel.getClassificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PASClient.PASService.getClassificationResponse> getClassificationAsync(string arg0) {
            PASClient.PASService.getClassificationRequest inValue = new PASClient.PASService.getClassificationRequest();
            inValue.Body = new PASClient.PASService.getClassificationRequestBody();
            inValue.Body.arg0 = arg0;
            return ((PASClient.PASService.IFileHandlerSEI)(this)).getClassificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PASClient.PASService.classifyResponse PASClient.PASService.IFileHandlerSEI.classify(PASClient.PASService.classifyRequest request) {
            return base.Channel.classify(request);
        }
        
        public void classify(string arg0) {
            PASClient.PASService.classifyRequest inValue = new PASClient.PASService.classifyRequest();
            inValue.Body = new PASClient.PASService.classifyRequestBody();
            inValue.Body.arg0 = arg0;
            PASClient.PASService.classifyResponse retVal = ((PASClient.PASService.IFileHandlerSEI)(this)).classify(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PASClient.PASService.classifyResponse> PASClient.PASService.IFileHandlerSEI.classifyAsync(PASClient.PASService.classifyRequest request) {
            return base.Channel.classifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PASClient.PASService.classifyResponse> classifyAsync(string arg0) {
            PASClient.PASService.classifyRequest inValue = new PASClient.PASService.classifyRequest();
            inValue.Body = new PASClient.PASService.classifyRequestBody();
            inValue.Body.arg0 = arg0;
            return ((PASClient.PASService.IFileHandlerSEI)(this)).classifyAsync(inValue);
        }
        
        public void createTree() {
            base.Channel.createTree();
        }
        
        public System.Threading.Tasks.Task createTreeAsync() {
            return base.Channel.createTreeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PASClient.PASService.uploadChatFileResponse PASClient.PASService.IFileHandlerSEI.uploadChatFile(PASClient.PASService.uploadChatFileRequest request) {
            return base.Channel.uploadChatFile(request);
        }
        
        public void uploadChatFile(string arg0) {
            PASClient.PASService.uploadChatFileRequest inValue = new PASClient.PASService.uploadChatFileRequest();
            inValue.Body = new PASClient.PASService.uploadChatFileRequestBody();
            inValue.Body.arg0 = arg0;
            PASClient.PASService.uploadChatFileResponse retVal = ((PASClient.PASService.IFileHandlerSEI)(this)).uploadChatFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PASClient.PASService.uploadChatFileResponse> PASClient.PASService.IFileHandlerSEI.uploadChatFileAsync(PASClient.PASService.uploadChatFileRequest request) {
            return base.Channel.uploadChatFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<PASClient.PASService.uploadChatFileResponse> uploadChatFileAsync(string arg0) {
            PASClient.PASService.uploadChatFileRequest inValue = new PASClient.PASService.uploadChatFileRequest();
            inValue.Body = new PASClient.PASService.uploadChatFileRequestBody();
            inValue.Body.arg0 = arg0;
            return ((PASClient.PASService.IFileHandlerSEI)(this)).uploadChatFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PASClient.PASService.downloadResponse PASClient.PASService.IFileHandlerSEI.download(PASClient.PASService.downloadRequest request) {
            return base.Channel.download(request);
        }
        
        public byte[] download(string arg0) {
            PASClient.PASService.downloadRequest inValue = new PASClient.PASService.downloadRequest();
            inValue.Body = new PASClient.PASService.downloadRequestBody();
            inValue.Body.arg0 = arg0;
            PASClient.PASService.downloadResponse retVal = ((PASClient.PASService.IFileHandlerSEI)(this)).download(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PASClient.PASService.downloadResponse> PASClient.PASService.IFileHandlerSEI.downloadAsync(PASClient.PASService.downloadRequest request) {
            return base.Channel.downloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<PASClient.PASService.downloadResponse> downloadAsync(string arg0) {
            PASClient.PASService.downloadRequest inValue = new PASClient.PASService.downloadRequest();
            inValue.Body = new PASClient.PASService.downloadRequestBody();
            inValue.Body.arg0 = arg0;
            return ((PASClient.PASService.IFileHandlerSEI)(this)).downloadAsync(inValue);
        }
    }
}
